sudo: required
services: docker
before_install:
- docker pull lctt/lfs-book-build
- mkdir -p /tmp/output
- chown 1000:1000 /tmp/output
script: docker run --rm -it -v "$TRAVIS_BUILD_DIR:/home/build/repo" -v "/tmp/output:/home/build/lfs-systemd" lctt/lfs-book-build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: /tmp/output
  on:
    all_branches: true
